source 'https://rubygems.org'

gem 'virtus'
gem 'trollop'
gem 'minitest'
gem 'minitest-reporters'
gem 'terminal-table'
gem 'clipboard'
gem 'timeout'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'
gem 'puma'
gem 'mutations'
gem 'azure-storage', '~> 0.11.5.preview'
